"""
Defines the schemas for request and response validation using Pydantic.
"""

from pydantic import BaseModel, Field, root_validator, ValidationError


class PredictionInput(BaseModel):
    """
    Schema for input data required by the prediction endpoint.
    """
    input_text: str = Field(
        ...,
        min_length=1,
        max_length=500,
        regex=r"^[a-zA-Z0-9\s.,!?-]+$",
        description="A string input for the ML model to process. "
                    "Must be alphanumeric and can include common punctuation.",
        example="This is a valid input text for the model.",
    )

    @root_validator(pre=True)
    def validate_input_text(cls, values):
        """
        Perform additional validation checks on the input text.

        Args:
            values (dict): Dictionary of field values.

        Returns:
            dict: Validated field values.
        """
        input_text = values.get("input_text")

        if input_text is None:
            raise ValueError("The 'input_text' field is required and cannot be null.")
        if len(input_text.split()) < 2:
            raise ValueError("The input text must contain at least two words.")

        return values


class PredictionResponse(BaseModel):
    """
    Schema for the prediction response data.
    """
    prediction: str = Field(
        ...,
        description="The output generated by the ML model.",
        example="Processed: This is a valid input text for the model.",
    )